version: "3.9"
services:
  website:
    ports:
      - "80:80"
    build: './build/website'

  mysql:
    restart: always
    ports:
      - "3306:3306"
    build: './build/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: "super-secret-password"
      MYSQL_DATABASE: "my-wonderful-website"
    volumes:
      - /root/mysql:/var/lib/mysql
  mail-server:
    build: './build/mail'

  ansible:
    build: './build/ansible'

